version: '3'
services:
  mysql:
    image: docker.io/mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    env_file: .flaskenv
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}