.PHONY: run 
run:
	python3 run.py 

.PHONY: setup 
setup:
	sudo docker-compose up

.PHONY: down 
down:
	sudo docker-compose down 

.PHONY: push 
push:
	git status 
	git add .
	git commit -m "Generated by Makefile"
	git push origin main 

.PHONY: pull
pull:
	git pull origin main 